### ISSUE TITLE
Request for example code or use information

### ISSUE THREAD

**Issue by gwlucastrig** [mreutegg/laszip4j#1]
First off, let me say that I am very pleased to see this project. I have been thinking about implementing a LAZ file decoder for months, and was daunted by the complexity of the implementation. 

Would it be possible to post example code showing how to read data from an LAZ file? Perhaps it could go on the wiki page.  I would like to integrate the LAZ library into an application that reads and displays lidar files.  It already handles LAS files, but I would like to extend it to read LAZ files. I spent a couple of hours reading through your code, but am not sure of the best way to proceed.

Also, is there a discussion forum or group for this project?   

Thanks again and good luck with your project.

**Comment by mreutegg** [comment]
Thanks for your interest in laszip4j. As you noticed already, the current state of the library is not that user friendly. Right now it's simply an incomplete Java port of the LASzip and LAStools libraries. I'll update this issue when I have examples ready that are more useful. In the meantime you could try the main [Laszip](https://github.com/mreutegg/laszip4j/blob/master/src/main/java/com/github/mreutegg/laszip4j/lastools/Laszip.java) class as used by the example in the README.md.

**Comment by gwlucastrig** [comment]
Thanks for the advice.  I will follow your suggestions.   

I look forward to seeing the progress of laszip4j in the future.  Your software has a great deal of potential application in my own github  [Tinfour project](https://github.com/gwlucastrig/Tinfour) and I am sure other developers will find it valuable as well.

**Comment by mreutegg** [comment]
I just added some convenience classes that make it easier to read point data from LAZ files. See the updated README. The changes are not yet released but you can still try them by building and using current master branch.

**Comment by gwlucastrig** [comment]
Thanks, Marcel.  I'll let you know how it goes.

**Comment by gwlucastrig** [comment]
Marcel,

Did a quick experimental integration of your code into the Tinfour viewer.  Downloaded an LAZ file from the Canton of Zurich website you referenced and was able to plot it.  The only difficult part was reading German :-)

![tinfourcantonofzurich](https://cloud.githubusercontent.com/assets/19698145/21703214/72c18fd4-d37e-11e6-9508-4ae6666b3d9a.jpg)

**Comment by gwlucastrig** [comment]
As I mentioned in my last post, I was able to integrate support for LAZ files in an experimental version of my Tinfour viewer.  I would like to add this capability to the version I distribute through the [Tinfour Project](https://github.com/gwlucastrig/Tinfour). Do you feel that your library is ready to be distributed as part of a separate application?   Would doing so be okay with you?

If you would prefer to discuss this matter separately from this tracker item, my email information is given in my github profile.

Thanks again for your excellent work!

**Comment by gwlucastrig** [comment]
Have a question about your API.   I don't seem to be able to get access to a LAS "withheld" status in the LASpoint class.  Is there a way to do that?   Does the LASReader iterator automatically screen out withheld samples?

Thanks.

**Comment by mreutegg** [comment]
You are right. Some flags were missing in the LASPoint class. I added accessors for "Synthetic", "Key-point" and "Withheld" flags and released laszip4j 0.3.

I'm not sure about the withheld samples, but I think the reader does not automatically filters them out.

**Comment by gwlucastrig** [comment]
Thanks

**Comment by gwlucastrig** [comment]
Marcel,

Is there a way to get a point value for a record in the LAZ file by record number or index.  In my application, I have a function that lets the user get the sample closest to a particular pair of points.  To build the display, I only retain a partial set of data (raw x, y, z, and index) and use a random-access operation to pull up the full set of data for the sample selected by the user (intensity, return number, time stamp, etc.).   I can do this with a LAS file and it looks like Martin Isenburg's design is intended to support random access.  Has that been implemented in the laszip4j API?

Thanks.

**Comment by mreutegg** [comment]
The LASReader now has additional methods to restrict the returned points to a tile, rectangle or circle. Those are the same as available for LAStools. An index file created by lasindex will speed up access. See also https://www.cs.unc.edu/~isenburg/lastools/download/lasindex_README.txt
