### ISSUE TITLE
Inverted Colours

### ISSUE THREAD

**Issue by maozturk** [mreutegg/laszip4j#10]
Hello,

We've some LASzip files which we try to decompress by using laszip4j. But, when we read the data from the file, colours are inverted, if the original colour is 55, it gives 200, it returns 0 for white colours, 255 for blacks.

Have you ever faced such a this problem? Do you have any idea why could it be happening?

Here is output of lasinfo : 

Here is output of lasinfo : 

lasinfo file1.laz
lasinfo (180209) report for file1.laz
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             0
  global_encoding:            0
  project ID GUID data 1-4:   00000000-0000-0000-0000-000000000000
  version major.minor:        1.2
  system identifier:          'libLAS'
  generating software:        'libLAS 1.7.0'
  file creation day/year:     304/2017
  header size:                227
  offset to point data:       227
  number var. length records: 0
  point data format:          2
  point data record length:   26
  number of point records:    155134505
  number of points by return: 0 0 0 0 0
  scale factor x y z:         0.001 0.001 0.001
  offset x y z:               73812.5 165062.5 415.5
  min x y z:                  73750.000 165000.000 353.000
  max x y z:                  73875.000 165125.000 478.000
LASzip compression (version 2.4r1 c2 50000): POINT10 2 RGB12 2
reporting minimum and maximum for all LAS point record entries ...
  X              -62500      62500
  Y              -62500      62500
  Z               21151      54218
  intensity           0          0
  return_number       0          0
  number_of_returns   2          6
  edge_of_flight_line 0          0
  scan_direction_flag 0          0
  classification      0          0
  scan_angle_rank  -128        127
  user_data           0        254
  point_source_ID   511       1050
  Color R 0 65025
        G 0 65025
        B 0 65025
number of first returns:        155134505
number of intermediate returns: 0
number of last returns:         0
number of single returns:       0
WARNING: there are 155134505 points with return number 0
overview over number of returns of given pulse: 0 29575050 39620204 45023717 31206905 9708629 0
histogram of classification of points:
       155134505  never classified (0)

Regards.

**Comment by mreutegg** [comment]
I'm not able to reproduce this with a sample laz file processed with las2las to set specific RGB values (using  -set_RGB option). Reading that file again with laszip4j gives the same values as previously set.

**Comment by maozturk** [comment]
I can still reproduce the issue with the following data:
https://drive.google.com/open?id=1YMCqUF0rYSZC-X5hSwTMwe0xSZ4ogN5R
