### ISSUE TITLE
Las 1.4

### ISSUE THREAD

**Issue by JoaLinde** [mreutegg/laszip4j#14]
Hello, 
while I was able to access LAS 1.2 files with laszip4j, it fails with LAS 1.4 files. Is it not implemented or did I something wrong in my implementation?

Thanks
Joachim

**Comment by mreutegg** [comment]
Hi Joachim,

I quickly tried with a LAS 1.4 file from here: https://dc-lidar-2018.s3.amazonaws.com/index.html and you are right, they cannot be read. It appears the read process fails because of a TODO in the code here: https://github.com/mreutegg/laszip4j/blob/laszip4j-0.7/src/main/java/com/github/mreutegg/laszip4j/laszip/LASreadPoint.java#L135

**Comment by mreutegg** [comment]
Current master contains above change that fixes the issue for me. The test added to LASReaderTest is able to read a LAS 1.4 file.

**Comment by JoaLinde** [comment]
Hi Marcel,
thank you for your quick response. I can confirm that LAS 1.4 files work. 
Sorry, but still there is problem with the compressed LAZ 1.4 files. So, when you compress your example las-file with the original laszip.exe, then laszip4j is not able to access. The error message is:
ERROR: compressor 3 not supported (LASzip v2.4r1)
       please upgrade to the latest release of LAStools (with LASzip)
       or contact 'martin.isenburg@rapidlasso.com' for assistance.
I am not sure if this has to do with the source code of laszip4j or with the installation / access to laszip?

**Comment by mreutegg** [comment]
The laszip4j library is a Java port of the original laszip tool created about three years ago. Maybe the laszip.exe you used is more recent and introduced some new feature not supported by this Java port. Can you please create a new issue for the problem you described?
