### ISSUE TITLE
LAZ 1.4

### ISSUE THREAD

**Issue by JoaLinde** [mreutegg/laszip4j#15]
Hello,

while the access to Las 1.4 works fine, my implementation crashes with the compressed LAZ 1.4 format (while the compressed LAZ 1.2 works fine). 

The error message is:

ERROR: compressor 3 not supported (LASzip v2.4r1)
please upgrade to the latest release of LAStools (with LASzip)
or contact 'martin.isenburg@rapidlasso.com' for assistance.

**Comment by mreutegg** [comment]
You are right, some part of the LAZ 1.4 format is not supported.

**Comment by jason-daly** [comment]
Hi Marcel,
I am looking at this lib currently in the context of an Apache Spark project.
I need to be able to support all released LasZIP versions.

Would you entertain reviewing a PR if I added support for LasZIP v 3.4? Else, I will do it on a fork.
Let me know.
Thanks,
Jason

**Comment by mreutegg** [comment]
Hi @jason-daly,

Sure, I'd be happy to review a PR with support for LAZ 1.4 format.

Regards
 Marcel

**Comment by jason-daly** [comment]
HI Marcel,
I am ready to submit a pull request. Can you grant me permissions to push my branch?

I see this, at the moment:
Permission to mreutegg/laszip4j.git denied to jason-daly
unable to access 'https://github.com/mreutegg/laszip4j.git/': The requested URL returned error: 403

Regards,
Jason

**Comment by mreutegg** [comment]
Hi Jason 

Please fork the repository and push the branch to your fork. You can then open a pull request with your branch and this repository.

Regards
 Marcel
