### ISSUE TITLE
How to use the laz file transform xyzk File

### ISSUE THREAD

**Issue by KilleTom** [mreutegg/laszip4j#16]
I have a laz file , if I wanted make laz file transform xyzk file, how to do that?

**Comment by mreutegg** [comment]
The readme has an example how to do that: https://github.com/mreutegg/laszip4j/blob/master/README.md

**Comment by KilleTom** [comment]
how？ I cant't see some sample code,your code don‘t have annotation，I don't known how use it to be a right xyzk file.
