### ISSUE TITLE
How to make laz file to be a  xyzk File

### ISSUE THREAD

**Issue by KilleTom** [mreutegg/laszip4j#17]
your project tools don't have java.doc and Related notes，that make me unknown how to use.
and your readme file don't have detail sample code, I can't known how to use the LASReader make
laz file to write a xyzk file, I see your project have many writer class, but they don't have about then
 note，so can you help me how to use that? I hope your can writer about sample code。because 
just the code and not uml or note 、description。that can't make people easy to usefully

**Comment by mreutegg** [comment]
As mentioned in the https://github.com/mreutegg/laszip4j/blob/master/README.md:

> Usage is the same as with the native laszip utility, but invoked as a runnable jar:

`java -jar laszip4j-0.5.jar -oparse xyzc -keep_class 3 4 5 6 10 -i 7015_2640.laz -o 7015_2640.xyzk`
