### ISSUE TITLE
pom

### ISSUE THREAD

**Issue by DarcyLeeDuni** [mreutegg/laszip4j#18]
how many plugin and dependency are can not download

**Comment by mreutegg** [comment]
Recent builds with maven 3.6.3 and Java 11 worked for me. Please add more details if something does not work.

**Comment by DarcyLeeDuni** [comment]
always appear can not resolve maven-release-plugin but already download success.

**Comment by mreutegg** [comment]
Cannot reproduce. Closing this issue.
