### ISSUE TITLE
How to access EXTENDED VARIABLE LENGTH RECORDS (EVLR)?

### ISSUE THREAD

**Issue by DawidLokiec** [mreutegg/laszip4j#32]
Hi,
frist of all thank you for the lib. Accroding to the LAS specification 1.3 (and 1.4) there are EXTENDED VARIABLE LENGTH RECORDS (EVLR). How can I access them using your lib? I see only the following API:
- LASReader#getHeader()
- LASReader#getPoints()
- LASHeader#getVariableLengthRecords()

I am **missing** something like `getExtendedVariableLengthRecords()`.

Many thanks in advance.

Dawid

**Comment by mreutegg** [comment]
Hi Dawid

This shouldn't be too difficult to add. Quite a bit of code has already been ported from laslib. Do you have publicly accessible data I can use for a test?

Regards
 Marcel

**Comment by DawidLokiec** [comment]
Hi Marcel,
thank you for the fast replay. Unfortunately I don't have any test data for you. I just searched for an LAS/LAZ-Parser in the Java-ecosystem for my own project and found your lib. While playing with your lib I just saw the missing ExtendedVariableLengthRecords-getter. It would be nice if you could add this getter too, so I could stick with your lib.

Regrads,
Dawid

PS: Is it a bug or feature `lasHeader.getNumberOfVariableLengthRecords() != Iterators.size(lasHeader.getVariableLengthRecords().iterator())`?
lasHeader.getNumberOfVariableLengthRecords() = 0
Iterators.size(lasHeader.getVariableLengthRecords().iterator()) = 1

**Comment by mreutegg** [comment]
> Is it a bug or feature

Why can't it be both? ;)

The implementation ported from laslib excludes VLRs created by laszip from the size calculation.
https://github.com/mreutegg/laszip4j/blob/master/src/main/java/com/github/mreutegg/laszip4j/laslib/LASreaderLAS.java#L817

But `LASReader.getNumberOfVariableLengthRecords()` exposes all of them. It should probably exclude the laszip header to be consistent.

**Comment by mreutegg** [comment]
The issue with the VLR size mismatch is now fixed in master: https://github.com/mreutegg/laszip4j/commit/90645ca56881b5698b90340612a3a84d2eebece4

**Comment by mreutegg** [comment]
https://github.com/mreutegg/laszip4j/pull/62 added a method to expose extended variable length records in the header.
