### ISSUE TITLE
Create a Java wrapper laszip.dll

### ISSUE THREAD

**Issue by taminhluan** [mreutegg/laszip4j#36]
I'm trying to use JNA to make a wrapper. But I'm stuck.

This is my procedure:

laszip_create(&laszipReader);
laszip_open_reader(&laszipReader, "test.las", is_compressed=false);

But it's raised: "writer is already open"

Please see [My code](https://github.com/taminhluan/LAStoolJNA/blob/master/src/main/java/LaszipApi.java)

and [laszipdllexample](https://github.com/LAStools/LAStools/blob/master/LASzip/example/laszipdllexample.cpp)

**Comment by mreutegg** [comment]
This is the wrong project to open such an issue. laszip4j is a pure Java port of [LASzip](https://github.com/LASzip/LASzip) and [LAStools](https://github.com/LAStools/LAStools). There is no need to use JNA on top of laszip4j.
