### ISSUE TITLE
Support random access of samples from file

### ISSUE THREAD

**Issue by gwlucastrig** [mreutegg/laszip4j#5]
As I've mentioned in the past, I am using laszip4j in an interactive application that allows the user to display lidar data (see  [https://github.com/gwlucastrig/Tinfour](url)  ).  It is working quite well for me and I would like to do more with it.

One of the functions of the application is to allow the user to click on the display and obtain data for the particular lidar sample point at the indicated position.  Due to the large number of samples in a lidar file and the limitations of memory,  I only retain the bare minimum of elements in memory (x, y, z, classification, and sample record number).  So when the user requests a full report on a sample, the application needs to re-read it from the source data file.

When the application is working with non-compressed LAS files, which have fixed-length records, the application can use the record number to compute a file position and extract a record at random.  So when the user clicks on a sample, the application opens the file, reads the record of interest, and  gives the user a full report of the data available for the sample (including GPS time, return number, intensity, scan angle rank, RGB, etc.).  I would like to support doing the same thing for LAZ files (which do not have a fixed record length).   To do so, I need a way to read a particular record at random.

Does laszip4j have an API that will allow me to do this?  If so, do you have example code or documentation I can use to implement that function?

One way to accomplish this function, of course, is to simply re-read the entire data file when the user cIicks on the screen, and discard all except the sample of interest. That will work, but it would probably be too slow for an interactive application.  I know that Martin Isenburg designed the laszip format so that samples would be compressed in blocks of 50000.   So if the application knows the starting position of all the blocks, it should be possible to extract just the block that includes the sample of interest (reading a block of 50000 points should be a lot faster than reading several million).  I know that there is a class that lets an application create an index for a LAZ file.  So some of the pieces for accomplishing this function do exist.  But I've looked through the code and don't see a mechanism for reading a single block.  Is there a way to do so?

Thanks.

**Comment by mreutegg** [comment]
The LASReader class already support this with the insideTile(), insideCircle() and insideRectangle() methods. The implementation makes use of a LAZ index if available (same filename but with .lax extension). The native lasindex tool is described [here](https://www.cs.unc.edu/~isenburg/lastools/download/lasindex_README.txt).

There is some experimental test code I created a while ago that [creates a LAZ index with laszip4j](https://gist.github.com/mreutegg/d7548309b9f24aadadb70f15ecf1ca5f), but I didn't look into it in more detail. Maybe you can use it as a starting point.

**Comment by mreutegg** [comment]
I'm closing this issue because I think the mentioned methods provide the desired functionality.
