### ISSUE TITLE
input / output stream

### ISSUE THREAD

**Issue by flashpixx** [mreutegg/laszip4j#52]
It would be nice that a las can read by any InputStream and write to any OutputStream, because in my case I working with an S3 storage and so I don't h ave got any files, I have got streams only.

My goal is to convert an InputStream with a LAS into an OutputStream with LAZ, so need something like

```java
try
(
    final las = new LasReader( myLASINputStream );
    final laz = new LazWriter( myLAZOutputStream ); 
)
{
    IOUtil.pipe( las, laz );
}
```

**Comment by mreutegg** [comment]
Reading from a stream is now possible. See changes introduced with https://github.com/mreutegg/laszip4j/pull/54

The new method `LASReader.getPoints(InputStream)` allows you to read LAS points from a stream. The stream must be from a .las file. The new laszip4j 0.9 release contains this improvement.

Writing a compressed .laz file is currently not supported by laszip4j. This port of [laszip](https://github.com/LASzip/LASzip) is not complete and writing laz files is one feature that is not implemented. See also https://github.com/mreutegg/laszip4j/issues/3
