### ISSUE TITLE
Making LASreadItemCompressed implementations accessible

### ISSUE THREAD

**Issue by maozturk** [mreutegg/laszip4j#6]
Hello,
Some implementations of the LASreadItemCompressed have package-private constructors and it's not possible to create an instance from them, I think it would be more useful if we would make their constructor public to make the API classes more accessible. If you agree with me, I can make the changes and create a PR for that.

Regards.

**Comment by mreutegg** [comment]
Sure, please create a PR.

**Comment by maozturk** [comment]
OK, I've completed the changes and created a PR.

**Comment by mreutegg** [comment]
Thanks for your contribution I merged your pull request.

**Comment by mreutegg** [comment]
Your changes have been included in the laszip4j-0.5 release.
