### ISSUE TITLE
Potential for negative classifications

### ISSUE THREAD

**Issue by jason-daly** [mreutegg/laszip4j#65]
Hi,
I found a bug in some of the code I wrote last year...
In the LASreadItemRaw_POINT14 class, the classification byte is read into a signed byte (-127..127), but needs to be read as an unsigned byte (0..255). 

I have a fix for it, and will submit a PR.

Regards,
Jason Daly

**Comment by mreutegg** [comment]
Thanks for the PR. I merged it.
