### ISSUE TITLE
Invalid method used in LASPoint::isKeyPoint

### ISSUE THREAD

**Issue by jandam** [mreutegg/laszip4j#89]
https://github.com/mreutegg/laszip4j/blob/9704e9d56e175d7966c137c87bdc6155ce9a98f9/src/main/java/com/github/mreutegg/laszip4j/LASPoint.java#L105

Correct implementation should use LASpoint::getKeypoint_flag instead of LASpoint::getSynthetic_flag

    public boolean isKeyPoint() {
        return p.getKeypoint_flag() == 1;
    }

**Comment by mreutegg** [comment]
Thank you for reporting.

This is fixed with https://github.com/mreutegg/laszip4j/pull/94
