### ISSUE TITLE
Points not written in output file

### ISSUE THREAD

**Issue by mghildiy** [mreutegg/laszip4j#9]
Hi, 

I run the program in IDE with my inputs as:

`String[] myArgs = {"-oparse", "xyzc", "-keep_class", "3", "4", "5" ,"6", "10",
                "-i", "path\\to\\my\\lazfile",
                "-o", "path\\to\\my\\output.xyzk"};

Laszip.main(myArgs);`

output.xyzk is created but no data is dumped in it.
On debugging it seems following code on line 654 in Laszip.java is the cause:

`while (lasreader.read_point())
 {
   laswriter.write_point(lasreader.point);
 }`

laswriter.write_point(lasreader.point) is never executed.
lasreader.read_point() does read points from .laz input file.

@mreutegg

**Comment by mghildiy** [comment]
I was able to solve my problem by modifying method read_point_filtered in LASreader.java.

I changed from 

> if (!filter.filter(point))

to

> if (filter.filter(point))

But I am not sure how it impacts overall behaviour of the program.

**Comment by mreutegg** [comment]
This most likely means the laz file does not have any point data with the classes specified by the -keep_class option. You may want to try without the option and check what classes the points have.
