### ISSUE TITLE
Should laszip4j support Java 8?

### ISSUE THREAD

**Issue by jandam** [mreutegg/laszip4j#90]
I would like to ask if laszip4j should support Java 8?
It is compiled with class target: Java 8 but with Java >= 9.
Problem is with calling: buffer.rewind() in:
 ByteStreamInDataInput.java
 ByteStreamOutDataOutput.java
 ByteStreamOutFile.java

In Java 8 buffer.rewind return Buffer type. For Java >= 9 rewind is redefined in ByteBuffer to return ByteBuffer type.
It means that laszip4j can't be run in Java 8 because different method descriptor.
  Thank you

**Comment by mreutegg** [comment]
Ah, right. That was a nasty breaking change.

This should be fixed with https://github.com/mreutegg/laszip4j/pull/96

Java 11 is now required to build, but laszip4j should run also on Java 8.
